### ISSUE TITLE
Correction of peg hole depth needed in some STL files.

### ISSUE THREAD

**Issue by revident** [FrameworkComputer/Mainboard#26]
To whom it concerns,

In the following STLs, the peg hole depth is to shallow to receive the pegs.
- [top_cover_r_cut.stl](https://github.com/FrameworkComputer/Mainboard/blob/67e1f079660176def138262ad7989c0090e32ca3/Mechanical/Printable%20Case/top_cover_r_cut.stl)
- [top_cover_r_full.stl](https://github.com/FrameworkComputer/Mainboard/blob/67e1f079660176def138262ad7989c0090e32ca3/Mechanical/Printable%20Case/top_cover_r_full.stl)

For those that don't have a suitable CAD application to do the adjustment themselves, a re-export would be appreciated.

Love the case, and much love to the Framework Team.

**Comment by eclecticc** [comment]
Thanks for catching that.  Closed in 5adf944a1dc8846e915730f52aa60e26a48eaa5e
