### ISSUE TITLE
Input connector pinout mismatch

### ISSUE THREAD

**Issue by CRImier** [FrameworkComputer/Mainboard#5]
https://github.com/FrameworkComputer/Mainboard/blob/main/Electrical/Pinouts.md#input-cover-interface=

Pins 30 and 32 are both KBL_P, looks like a copy-paste error, one of them ought to be KBL_N

**Comment by eclecticc** [comment]
GND is the other end of KBL_P.  Two pins are used due to the potential current needs.

**Comment by CRImier** [comment]
o h
thank you, wonderful to know - I almost made a board that would've been faulty! fixing!
