### ISSUE TITLE
Input board connector part number confirmation

### ISSUE THREAD

**Issue by CRImier** [FrameworkComputer/Mainboard#6]
Designing a PCB mating with the input board connector, I've noticed that motherboard pictures showing the input connector don't match the Pinouts.md-stated 10156000 connector pictures on Mouser and Amphenol website. For instance, there's large pads to the sides of the connector, which are not present on the Amphenol 10156000 connector (and not just pictures - they aren't shown in the connector drawings and recommended footprint, either).

Motherboard picture:
![image](https://user-images.githubusercontent.com/3173633/167281756-2db1ed21-7845-4de8-b089-06dfaa37fcd6.png)
[Mouser](https://eu.mouser.com/ProductDetail/Amphenol-FCI/10156000-051100LF) and [Amphenol website](https://www.amphenol-cs.com/bergstak-0-50mm-self-alignment-10156000051100lf.html) picture of the connector
![image](https://user-images.githubusercontent.com/3173633/167281760-4464693b-6e5d-4b75-8115-c6b0af257825.png)

Insights?

**Comment by CRImier** [comment]
![image](https://user-images.githubusercontent.com/3173633/167283045-97674152-e7f3-439c-99e5-ba13892e1e13.png)
Hmm, seems like I've been referring to an outdated motherboard picture? Lack of pictures is a bit of a problem.

**Comment by eclecticc** [comment]
Yep, the image with the ground tabs was an early prototype that used a different connector.
